# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Took here from https://github.com/anitab-org/mentorship-flutter/blob/develop/.github/workflows/flutter-ci.yml
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    
    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v2.3.1
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
    
    # Get flutter dependencies.
    - run: flutter pub get
    
    # Run tests for our flutter project once we add unit tests.
    # - run: flutter test
    
    # Build apk.
    - run: flutter build apk
    
    # Build ios
    - name: Run ios build
      if: ${{ matrix.platform == 'macos-latest'}}
      run: flutter build ios --release --no-codesign 
    
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v2
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk
